### PR TITLE
App name should not be translated

### PR DESCRIPTION
**Pull request by licaon-kter**
and an ellipsis

### CODE REVIEW

**Comment by Nutomic** [comment]
I disagree, it should be possible to translate the app name, eg for languages that use a different alphabet.

And can you please combine your PRs into one?

**Comment by licaon-kter** [comment]
The ellipsis and the typo, minus the app name?

**Comment by Nutomic** [comment]
Yes exactly.

**Comment by licaon-kter** [comment]
fixed on #27

**Pull request closed without merging**
