### PR TITLE
Externalized strings + german translation

### PR DESCRIPTION
**Pull request by ImPat**
I externalized a lot of strings found in the java/kotlin code. There are still some things that need externalization. In layout for example. I don't know if it works, because android studio can't compile the apk. I may externalize the strings in layout if I manage to compile it. 
Heres the error I got:
```
C:\<redacted>\syncthing-lite\app\src\main\kotlin\net\syncthing\lite\library\DownloadFileTask.kt
Error:(34, 35) Type mismatch: inferred type is FileInfo but String was expected
Error:(34, 46) Type mismatch: inferred type is (???) -> Unit but String was expected
Error:(34, 48) Cannot infer a type for this parameter. Please specify it explicitly.
Error:(58, 10) No value passed for parameter 'listener'
Error:Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details
```
Note: I didn't modify this file in any way, nor do I have any experience with compiling apks.

### CODE REVIEW

**Comment by ImPat** [comment]
I actually don't mind translating it to German. I don't have anything else to do, so why not?

**Comment by ImPat** [comment]
Ok! I figured it out! The issue is commit https://github.com/Nutomic/syncthing-lite/commit/e566b3c58d83be9a90a6c4df19cd8457b19aa783. I think I can fix this myself!

**Comment by ImPat** [comment]
Don't merge this yet. I still have some work to do.

**Comment by ImPat** [comment]
Might be ready for merging. Unfortunately, I can't test the parts that require a folder since I can't add one.

**Comment by ImPat** [comment]
Ready for merging I hope.

**Comment by Nutomic** [comment]
Actually, the compile error is because I'm currently doing some changes to the library interface. To compile, you will have to clone the latest version of [syncthing-java](https://github.com/Nutomic/syncthing-java) and `gradle install` it.

Und danke fürs übersetzen :)

**Comment by ImPat** [comment]
No idea how to do that on windows(android studio). I tried doing gradle install in git bash but it I don't have it installed apparently. I didn't know that syncthing java was causing this so I didn't spend a lot of time attempting to fix it.

**Comment by Nutomic** [comment]
It should work if you execute `gradlew.bat install` in the normal windows terminal (not sure about the exact syntax). Or just revert the code change in DownloadFileTask.kt and I will make sure that it compiles.

**Comment by ImPat** [comment]
Reverted.

**Comment by Nutomic** [comment]
Thanks!

**Pull request merged**
